# Generated by Django 4.2.13 on 2024-05-20 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watchlists", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watchlist",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(name="watchlist", table="watchlists",),
    ]
